### PR TITLE
Fix ERB templates for puppet 4

### PR DESCRIPTION
**Pull request by danieldreier**
Use @syntax for ERB template variables to fix Puppet 4 compatibility.

### CODE REVIEW

**Comment by danielparks** [comment]
FWIW, +1

**Comment by igalic** [comment]
@danieldreier wanna rebase this?

**Comment by danielparks** [comment]
Looks like this has all been updated already. Closing!

**Comment by thrnio** [comment]
undeleted the branch because we're apparently still using that ref

**Comment by danielparks** [comment]
Sigh.

**Pull request closed without merging**
